-- 1. 
SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE
				   WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';

-- 2. 
SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE
			    WHERE EXTRACT (YEAR FROM HIRE_DATE) > 2000);

-- 3.
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
							   FROM EMPLOYEE 
							   WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';

-- 4. 
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, HIRE_DATE
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE 
							   FROM EMPLOYEE
							   WHERE EXTRACT (YEAR FROM HIRE_DATE) = 2000);
							  
-- 5. 
SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, HIRE_DATE 
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) = (SELECT DEPT_CODE, MANAGER_ID
								 FROM EMPLOYEE
								 WHERE SUBSTR(EMP_NO, 1, 2) = '77'
								 AND SUBSTR(EMP_NO, 8, 1) = '2');					  

-- 6. 소속없음 확인
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE 
FROM EMPLOYEE MAIN
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) 
				   FROM EMPLOYEE SUB
				   WHERE ENT_YN = 'N'
				   AND NVL(MAIN.DEPT_CODE, 1) = NVL(SUB.DEPT_CODE, 1) 
				   GROUP BY DEPT_CODE)
ORDER BY HIRE_DATE;

-- 7. 
/*IN 사용 시 신뢰도 낮음*/
SELECT EMP_ID, EMP_NAME, JOB_NAME, 
	   EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')) -1 "만 나이",
	   TO_CHAR((SALARY + (SALARY * NVL(BONUS, 0))) * 12, '999,999,999L') "보너스 포함 연봉"
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE (JOB_CODE, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')))
 IN (SELECT JOB_CODE, MIN(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')))
     FROM EMPLOYEE 
     GROUP BY JOB_CODE)
ORDER BY "만 나이" DESC;

/* = 사용 */
SELECT EMP_ID, EMP_NAME, JOB_NAME, 
	   EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')) -1 "만 나이",
	   TO_CHAR((SALARY + (SALARY * NVL(BONUS, 0))) * 12, '999,999,999L') "보너스 포함 연봉"
FROM EMPLOYEE 
JOIN JOB ON (EMPLOYEE.JOB_CODE = JOB.JOB_CODE)
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD'))
 = (SELECT MIN(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD')))
    FROM EMPLOYEE 
    WHERE NVL(EMPLOYEE.JOB_CODE, 1) = NVL(JOB.JOB_CODE, 1))
ORDER BY "만 나이" DESC;



