-- 1. 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) IN (2, 4);

-- 3. 나이가 마이너스?????????????????????????????????????????????
SELECT PROFESSOR_NAME 교수이름, 
	   EXTRACT(YEAR FROM SYSDATE) 
	   - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD')) 나이
FROM TB_PROFESSOR tp 
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD')) DESC;

-- 4. 
SELECT SUBSTR(PROFESSOR_NAME, -2, 2) 이름
FROM TB_PROFESSOR;

-- 5. 
--SELECT STUDENT_NO, STUDENT_NAME 
--FROM TB_STUDENT
--WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD')) != 19;

-- 6.
--SELECT TO_DATE('2020-12-25', 'YYYY-MM-DD')
--FROM DUAL;

-- 7. 
--SELECT 
--FROM 

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
--WHERE EXTRACT (YEAR FROM ENTRANCE_DATE) LIKE '1%';
WHERE STUDENT_NO NOT LIKE 'A%'; 

-- 9.
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
--SELECT DEPARTMENT_NO "학과번호", CAPACITY "학생수(명)"
--FROM TB_DEPARTMENT
--GROUP BY DEPARTMENT_NO, CAPACITY;

-- 11. 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY SUBSTR(TERM_NO, 1, 4);

-- 13. 휴학생 0명 ?????????????????????????????????????????
SELECT DEPARTMENT_NO 학과코드명, COUNT(ABSENCE_YN) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 
SELECT STUDENT_NAME "동일이름", COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) >= 2
ORDER BY STUDENT_NAME;

-- 15.
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, -2, 2) 학기, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, -2, 2))
ORDER BY 년도, 학기;



